/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:c636bf1a-a8bf-48a6-93e8-1eab9d92c5ae",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_iKfZ4ev22",
    "aws_user_pools_web_client_id": "4ijae4rn4lfa3svkvpqc23umar",
    "oauth": {},
    "aws_user_files_s3_bucket": "awsappsyncreactjswor966db111423a4586a5c5343b053122306-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://z7fwr6cyxjauzbxheiow44dfjy.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
